papsign/Ktor-OpenAPI-Generator

gradle.properties
src/main/kotlin/com/papsign/ktor/openapigen/OpenAPIGen.kt
src/main/kotlin/com/papsign/ktor/openapigen/OpenAPIGenExtension.kt
src/main/kotlin/com/papsign/ktor/openapigen/OpenAPIGenModuleExtension.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/encodings/APIFormatter.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/binary/BinaryContentTypeParser.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/ktor/KtorContentProvider.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/multipart/MultipartFormDataContentProvider.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/OpenAPIRoute.kt
src/main/kotlin/com/papsign/ktor/openapigen/validators/LowerCase.kt
src/main/kotlin/com/papsign/ktor/openapigen/validators/Trim.kt
src/main/kotlin/com/papsign/ktor/openapigen/validators/ValidationAnnotation.kt
src/main/kotlin/com/papsign/ktor/openapigen/validators/ValidationHandler.kt
src/main/kotlin/com/papsign/ktor/openapigen/validators/Validator.kt
src/main/kotlin/com/papsign/ktor/openapigen/validators/util/AValidator.kt

Added support for transforming and validating annotations during serialization.
Currently Supported:
@LowerCase applies .toLowerCase on String
@Trim applies .trim on String
New validators can be added by declaring a new openapi module in the search path: 
in the config:
```kotlin
install(OpenAPIGen) {
...
scanPackagesForModules = arrayOf("com.example")
}
```
in `com.example.TestValidator`
```kotlin
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.PROPERTY)
annotation class TestAnnot
object AnyValidator : AValidator<Any, TestAnnot>(Any::class, TestAnnot::class) {
override fun validate(subject: Any?, annotation: TestAnnot): Any? {
println(subject)
// return transformed object or throw exceptions that you will handle with the route exception handlers
return subject
}
}
```

Created Transformers and validators for easy constraint resolution.

---

src/main/kotlin/com/papsign/ktor/openapigen/schema/builder/provider/NothingSchemaProvider.kt

Follow up of #26.
Thank you, but you variant puts `java.lang.Void` in the map so my `kotlin.Nothing?` isn't its subtype. I've made some changes and they work for me. Could you accept them to the main repo?

make Nothing provider provide nullable Nothing

---

README.md
build.gradle
src/main/kotlin/com/papsign/ktor/openapigen/OpenAPIGen.kt
src/main/kotlin/com/papsign/ktor/openapigen/SwaggerUI.kt

Making the version configurable means people can use a different version of `org.webjars:swagger-ui` with this library.

Update swaggerui, make its version configurable, minor readme update

---

src/main/kotlin/com/papsign/ktor/openapigen/annotations/properties/description/Description.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/properties/description/DescriptionProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/schema/SchemaModel.kt
src/test/kotlin/TestServer.kt

This PR adds support for annotating model properties to provide a description (see #52).
Sample usage:
```kotlin
@Response("A String Response")
data class StringResponse(
@Description("The string value") val str: String
)
```
Generated Swagger JSON:
```json
"StringResponse" : {
"nullable" : false,
"properties" : {
"str" : {
"description" : "The string value",
"nullable" : false,
"type" : "string"
}
},
"required" : [ "str" ],
"type" : "object"
}
```
Swagger UI:

Support model property descriptions

---

src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/example/StringExample.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/example/StringExampleProcessor.kt
src/test/kotlin/TestServer.kt

This PR adds support for simple string examples on string properties.
This is currently possible via `@WithExample`, but that approach requires creating an `ExampleProvider` for each property that returns the example string. 
Sample code:
```kotlin
@Response("A Response for header param example")
data class NameGreetingResponse(
@StringExample("Hello John") val str: String
)
```
Generated JSON:
```json
"NameGreetingResponse" : {
"nullable" : false,
"properties" : {
"str" : {
"example" : "Hi, John!",
"nullable" : false,
"type" : "string"
}
},
"required" : [ "str" ],
"type" : "object"
},
```
Swagger UI:

Add StringExample for easier examples of String properties

---

src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/common/ConstraintViolation.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/NumberConstraintProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/clamp/FClamp.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/clamp/FClampProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/max/FMax.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/max/FMaxProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/min/FMin.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/min/FMinProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/clamp/Clamp.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/clamp/ClampProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/max/Max.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/max/MaxProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/min/Min.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/min/MinProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/NotAStringViolation.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/Length.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/LengthConstraintProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/LengthProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/MaxLength.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/MaxLengthProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/MinLength.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/MinLengthProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/pattern/RegularExpression.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/pattern/RegularExpressionConstraintProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/pattern/RegularExpressionProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/schema/SchemaModel.kt
src/test/kotlin/TestServer.kt

String length can be validated using annotations (Length, MaxLength or MinLength)

Add validators for strings

---

src/main/kotlin/com/papsign/ktor/openapigen/content/type/BodyParser.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/binary/BinaryContentTypeParser.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/ktor/KtorContentProvider.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/multipart/MultipartFormDataContentProvider.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/OpenAPIRoute.kt

Using KType and `typeOf<B>` instead of B::class to preserve generic type info, so being able to receive something like `List<T>` as a body

Preserve generic type info when parse body

---

build.gradle
gradle.properties

Currently logback is defined as implementation dependency, this leads to projects using this library and having a different implementation of slf4j generating a warning. This can easily be fixed by depending on the slf4j-api instead of logback directly. The code already uses the api only.
Example warning:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/david/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.12.1/14973e22497adaf0196d481fb99c5dc2a0b58d41/log4j-slf4j-impl-2.12.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/david/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.1/706a8b8206ead3683ec639dd270d11fd948fbb0e/logback-classic-1.2.1.jar!/org/slf4j/ …
```

use slf4j api instead of direct logback dependency to avoid slf4j warnings about multiple bindings

---

src/main/kotlin/com/papsign/ktor/openapigen/KTypeUtil.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/BodyParser.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/ResponseSerializer.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/binary/BinaryContentTypeParser.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/ktor/KtorContentProvider.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/multipart/MultipartFormDataContentProvider.kt
src/main/kotlin/com/papsign/ktor/openapigen/modules/handlers/RequestHandlerModule.kt
src/main/kotlin/com/papsign/ktor/openapigen/modules/handlers/ResponseHandlerModule.kt
src/main/kotlin/com/papsign/ktor/openapigen/modules/handlers/ThrowOperationHandler.kt
src/main/kotlin/com/papsign/ktor/openapigen/parameters/util/Util.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/Functions.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/OpenAPIRoute.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/path/auth/Functions.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/path/auth/OpenAPIAuthenticatedRoute.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/path/normal/Functions.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/path/normal/NormalOpenAPIRoute.kt
src/main/kotlin/com/papsign/ktor/openapigen/validation/ValidationHandler.kt
src/test/kotlin/com/papsign/ktor/openapigen/routing/GenericsTest.kt
src/test/kotlin/com/papsign/ktor/openapigen/routing/RoutingTest.kt

When building routes with reflection instead of manually registering them it is not possible to use reified DSL because it is not available at runtime using reflection. This can be fixed by only using reified for DSL methods and passing the class instance as parameters. This would allow external code to build routes from for example something like this:
```kotlin
@Controller("/test")
class TestController {
@Throws(TestException::class, TestExceptionHandler::class) 
@Route("info", RouteHttpMethod.GET, "example info", "example description")
fun testRoute(params: String, body: String, ctx: APIRequestContext): String {
return params
}
}
```
There is no impact to the current DSL and there should be no performance impact, since this only affects the route building.

Allow explicit class references when building routes

---

src/main/kotlin/com/papsign/ktor/openapigen/APITag.kt
src/main/kotlin/com/papsign/ktor/openapigen/interop/StatusPages.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/security/FlowsModel.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/security/SecuritySchemeModel.kt
src/main/kotlin/com/papsign/ktor/openapigen/modules/providers/AuthProvider.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/Functions.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/Info.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/RouteConfig.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/path/auth/Functions.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/path/auth/OpenAPIAuthenticatedRoute.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/path/normal/Functions.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/response/OpenAPIPipelineResponseContext.kt

As discussed in issue #36, this pull request adds some comments to make it easier to understand the library.
This also renames some of the types used in templates to better explain what they are.
Some of the renamed types include:
- B -> TRequest
- R -> TResponse
- P -> TParams
- A -> TAuth
For now this pull request includes only the most common classes and functions so that the maintainers can review it and see if they are ok with these changes.

Some documentation and renamed template types

---

build.gradle
src/test/kotlin/JwtAuthDocumentationGenerationTest.kt
src/test/kotlin/TestServerWithJwtAuth.kt

Adds a test server demonstrating how JWT authentication can be implemented, and a test (CURRENTLY FAILING) using that test server that demonstrates that security scheme generation currently isn't working the way it did in 0.2-beta.7 (If the test is run in that version, it passes.)
To maintain green build, should NOT be merged until after the security scheme generation is fixed. 
Created to help solve issue #64

Adding test to demonstrate failing security scheme generation

---

src/test/kotlin/JwtAuthDocumentationGenerationTest.kt
src/test/kotlin/TestServerWithJwtAuth.kt

Bearer authentication should be done with the http type, not openIdConnect, now fixed in test server. Also changing name to a unique value to avoid confusion (it was previously equal to the bearerFormat).

Changing test server to correct JWT bearer auth config.

---

src/main/kotlin/com/papsign/ktor/openapigen/annotations/properties/description/Description.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/clamp/FClamp.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/max/FMax.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/floating/min/FMin.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/clamp/Clamp.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/max/Max.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/number/integer/min/Min.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/object/example/WithExample.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/example/StringExample.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/Length.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/MaxLength.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/length/MinLength.kt
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/pattern/RegularExpression.kt
src/main/kotlin/com/papsign/ktor/openapigen/parameters/handlers/ModularParameterHandler.kt

When annotations are applied in this way, the corresponding parameters were not applied to the schema model.
```kotlin
@Path("string/{str}")
data class StringParam(
@PathParam("A simple String Param")
@MinLength(2)
@MaxLength(10)
val str: String,
)
```

Fixed filling the schema model with annotations for query and params

---

src/main/kotlin/com/papsign/ktor/openapigen/SerializationSettings.kt
src/main/kotlin/com/papsign/ktor/openapigen/Util.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/DataModel.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/security/SecurityModel.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/security/SecuritySchemeModel.kt
src/test/kotlin/JwtAuthDocumentationGenerationTest.kt

Hello, this PR adds following improvements:
- proper serialization of SecurityModel in case of bearer ( empty scopes)
- skip "name" field when serializing SecuritySchemeModel
It also adds bit flexibility during serialization:
- basic settings for serailization that includes possibility of serializing empty lists/maps
- possibility to override serialization for nested DataModel
closes #79
closes #68

Improvements for jwt

---

README.md
src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/string/discriminator/LegacyDiscriminatorProcessor.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/ktor/KtorContentProvider.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/schema/Discriminator.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/schema/SchemaModel.kt
src/test/kotlin/JwtAuthDocumentationGenerationTest.kt
src/test/kotlin/OneOf.kt
src/test/kotlin/TestServer.kt

Tested on generators:
- TypeScript
- TypeScript-fetch 
Given:
- User is using subTypes to create polymorphic ode
Whe:
- Code is generated
Then
- Discriminators are not taken into account
Should:
- Code should be discriminators aware
Old behavior:
Generated code with discriminators not compiling
No discriminators:
```
export class Base {
'str': string;
'i': number;
static readonly discriminator: string | undefined = undefined;
static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
{
"name": "str",
"baseName": "str",
"type": "string",
"format": ""
},
{
"name": "i",
"baseName": "i",
"type": "number",
"format": "int32"
}    ];
static getAttributeTypeMap() {
return Base.attributeTypeMap;
}
public constructor() {
}
}
export class A {
'str': …
```

Fix for OneOf Subtyping - Generators were failing to generate proper discriminators

---

src/main/kotlin/com/papsign/ktor/openapigen/validation/ValidationHandler.kt
src/test/kotlin/TestServer.kt

Using copy method of data class for params  instead of changing java field

---

src/main/kotlin/com/papsign/ktor/openapigen/parameters/parsers/builders/query/deepobject/DeepBuilderFactory.kt
src/main/kotlin/com/papsign/ktor/openapigen/parameters/parsers/builders/query/deepobject/OptionalDeepBuilder.kt
src/main/kotlin/com/papsign/ktor/openapigen/parameters/parsers/converters/ConverterFactory.kt
src/main/kotlin/com/papsign/ktor/openapigen/parameters/parsers/converters/object/OptionalConverter.kt
src/main/kotlin/com/papsign/ktor/openapigen/schema/builder/provider/FinalSchemaBuilderProvider.kt
src/test/kotlin/com/papsign/ktor/openapigen/parameters/parsers/builder/query/form/OptionalBuilderTest.kt
src/test/kotlin/com/papsign/ktor/openapigen/parameters/parsers/builders/query/deepobject/OptionalBuilderTest.kt

Allow usage `Optional<T>?` in `@QueryParam` 
```
data class OptionalRequest(
@QueryParam("strictly optional", allowEmptyValues = true) val optInt: Optional<Int>? = null
)
```
Result
/request?optInt=1  > Optional.of(1)
/request?optInt=  > Optional.empty()
/request?optInt=null  > Optional.empty()
/request  > null

add java.util.Optional support

---

src/main/kotlin/com/papsign/ktor/openapigen/route/path/auth/Functions.kt
src/main/kotlin/com/papsign/ktor/openapigen/route/path/normal/Functions.kt
src/test/kotlin/com/papsign/ktor/openapigen/routing/GenericRoutesTest.kt

Fix UnsupportedOperationException (https://youtrack.jetbrains.com/issue/KT-34051 or may be similar) for generic routes:
```kotlin
inline fun <reified TNodeNew : TreeNodeNew, reified TNode : TreeNodeBase> NormalOpenAPIRoute.treeNodeRoute(
service: TreeNodeService<TNodeNew, TNode>
) {
route("{id}").get<PathId, List<TNode>> { params ->
respond(service.listNodes(params.id))
}
route("{id}").delete<PathId, Unit> { params ->
service.removeNode(params.id)
pipeline.call.respond(HttpStatusCode.NoContent)
}
get<Unit, List<TNode>> {
respond(service.listNodes(null))
}
post<Unit, TNode, TNodeNew> { _, body ->
respond(service.createNode(body))
}
patch<Unit, Unit, TNode> { _, body ->
service.updateNode(body)
pipeline.call.respond(HttpStatusCode.NoContent)
}
}
```
```
This function has a reified type …
```

Fix UnsupportedOperationException for generic routes

---

src/main/kotlin/com/papsign/ktor/openapigen/route/Info.kt

Right now `OperationModel.deprecated` is unused and cannot be changed without external modules.

Add deprecated operation flag into info() function

---

src/main/kotlin/com/papsign/ktor/openapigen/model/security/SecurityModel.kt
src/main/kotlin/com/papsign/ktor/openapigen/model/security/SecuritySchemeModel.kt
src/main/kotlin/com/papsign/ktor/openapigen/modules/handlers/AuthHandler.kt
src/test/kotlin/JwtAuthDocumentationGenerationTest.kt
src/test/kotlin/TestServerWithJwtAuth.kt
src/test/kotlin/com/papsign/ktor/openapigen/routing/GenericRoutesTest.kt

Fixes https://github.com/papsign/Ktor-OpenAPI-Generator/issues/114
Current `name` is used as a "reference" name to refer to that particular scheme in OpenAPI spec (in yaml or json it is key value of the map containing security schemas)
But [spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#securitySchemeObject) refers to `name` as a field in that object with very specific semantic
```The name of the header, query or cookie parameter to be used.```
After this change `name` will become what it is supposed to be - name of query/header/cookie, and for "reference" name there is a new required field.
This change will break those, who uses name as "reference" name, but it will bring library closer to OpenAPI spec.

Added support of name for cookies and query parameters in SecurityScheme

---

src/main/kotlin/com/papsign/ktor/openapigen/annotations/type/enum/StrictEnumParsing.kt
src/main/kotlin/com/papsign/ktor/openapigen/parameters/parsers/converters/primitive/EnumConverter.kt
src/test/kotlin/com/papsign/ktor/openapigen/EnumNonStrictTestServer.kt
src/test/kotlin/com/papsign/ktor/openapigen/EnumStrictTestServer.kt
src/test/kotlin/com/papsign/ktor/openapigen/EnumTestServer.kt
src/test/kotlin/com/papsign/ktor/openapigen/parameters/parsers/builder/query/form/EnumBuilderTest.kt
src/test/kotlin/com/papsign/ktor/openapigen/parameters/parsers/builders/query/deepobject/EnumBuilderTest.kt

It fixes https://github.com/papsign/Ktor-OpenAPI-Generator/issues/111 with throwing `OpenAPIBadContentException` on parsing wrong value.
This validation won't add anything to RouteSelectors, so you have to manually catch error via StatusPage ktor feature to show desired StatusCode and message to the user.
Which I think totally fine because current code throws `OpenAPIRequiredFieldException` on omitting non-nullable query parameter, so this is the same behavior.
Assuming we have enum parameter with name `type` and valid values: `[VALID]`
```
| Route        | StatusCode | Parsed Enum Value     |
|--------------|------------|-----------------------|
| /            | 200        | null                  |
| /?type=VALID | 200        | VALID                 |
| /?type=else  | 200        | null …
```

Added validation error on parsing enum values outside of valid enum values

---

src/main/kotlin/com/papsign/ktor/openapigen/content/type/multipart/FormDataRequest.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/multipart/FormDataRequestType.kt
src/main/kotlin/com/papsign/ktor/openapigen/content/type/multipart/MultipartFormDataContentProvider.kt
src/test/kotlin/OneOf.kt
src/test/kotlin/TestServer.kt
src/test/kotlin/com/papsign/ktor/openapigen/FormDocumentationGenerationTest.kt

This will add support for **application/x-www-form-urlencoded** content type in post requests.
Changes are backward compatible, I have also added tests.
Maybe It will be good to add some additional validations like ensure that no one defines file upload as form-urlencoded.
Just let me know what you think.
Regards

Support application/x-www-form-urlencoded content type
